name: build EXE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Visual Studio Developer Command Prompt einrichten
      uses: ilammy/msvc-dev-cmd@v1

    - name: Projekt mit MSBuild bauen
      run: msbuild Tetris.sln /p:Configuration=Release

    - name: Gefundene EXE-Dateien auflisten
      run: cmd /c "dir /s /b *.exe"

    - name: EXE als Artefakt hochladen
      uses: actions/upload-artifact@v4
      with:
        name: tetris-exe
        path: |
          **/Release/*.exe
